title: Rokokoo
description: Robotiikan koulutus kasvuyritysten ohjenuorana
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
github: 
  url: https://github.com/rokokoo/rokokoo.git
  username: mrgs20
  site_url: https://github.com/rokokoo/rokokoo.git